### ISSUE TITLE
[BFCL] Inconsistency in leaderboard scores

### ISSUE THREAD

**Issue by Double-bear** [ShishirPatil/gorilla#493] opened 2024-07-01 08:51 UTC
I use the code to reproduce the Llama3 8b instruct model score. In Abstract Syntax Tree (AST) Evaluation, my score of simple functions and Parallel Functions are much higher than the score on the leaderboard. However, the rest of my scores are almost similar to the leaderboard.

The leaderboard scores are:
Simple Function: 55.09
Multiple Functions: 73.5
Parallel Functions: 58
Parallel Multiple: 64

and my scores are: 
Simple Function: 66.5
Multiple Functions: 72
Parallel Functions: 63.5
Parallel Multiple: 60

May I ask if the scoring on the list is reproducible?

**Comment by HuanzhiMao** [comment] 2024-07-01 18:18
Hi @Double-bear, 
All the scores on the leaderboard are reproducible. You should be able to obtain a similar result (might be off by a little bit due to the temperature bring set to 0.7) by following the [README](https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/README.md) to run the generation script and the evaluation script.

**Comment by Double-bear** [comment] 2024-07-03 09:01
> Hi @Double-bear, All the scores on the leaderboard are reproducible. You should be able to obtain a similar result (might be off by a little bit due to the temperature being set to 0.7) by following the [README](https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/README.md) to run the generation script and the evaluation script.

Hi @HuanzhiMao . Thanks for your reply. However, I did run the code according to the process written in the readme. The only difference is the model, which is loaded from my local path. I don't think 0.7 temperature should make nearly a 10 point difference.

**Comment by HuanzhiMao** [comment] 2024-07-06 02:51
Hey @Double-bear, 
Llama3 models do seem to have a high variance in model results (and thus evaluation score). I re-regenerate another batch this afternoon and got the following result:
```
simple: 0.5855
     python: 0.6475
     java: 0.41
     javascript: 0.44
multiple: 0.745
parallel: 0.605
parallel_multiple: 0.555

executable_simple: 0.7235
     python: 0.77
     rest: 0.657
executable_multiple_function: 0.8
executable_parallel_function: 0.72
executable_parallel_multiple_function: 0.55

relevance: 0.467
```
In the future, we will set all model temperatures to 0 when inferencing to ensure reproducibility. See #500.

**Comment by ShishirPatil** [comment] 2024-07-25 07:14
Hey @Double-bear we'd recommend you try it again with temp 0.7? If that still doesn't work then please share with us your generations so we can debug 1-1? Since we can't repro it at the moment. Closing the issue, but please feel free to reopen it.

**Closed by ShishirPatil** 2024-07-25 07:14 UTC
Labels: apibench-data
